export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

/**
 * Login Related
 */

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

/**
 * Contacts
 */

export const CONTACTS_LOADING = "CONTACTS_LOADING";
export const CONTACTS_FAILED = "CONTACTS_FAILED";
export const CONTACTS_SUCCESS = "CONTACTS_SUCCESS";
